version: '3'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=CowWeb_ver1.settings
    volumes:
      - uwsgi-socket:/tmp
      - static-files:/app/static
      - ./entrypoint.sh:/app/entrypoint.sh  # 挂载 entrypoint.sh 到容器
    restart: always

  nginx-backend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/backend.conf
      - uwsgi-socket:/tmp
      - static-files:/app/static
      - ./entrypoint.sh:/app/entrypoint.sh  # 挂载 entrypoint.sh 到容器
      - certbot-etc:/etc/letsencrypt  # 用于存储证书
      - certbot-var:/var/www/certbot
    depends_on:
      - web
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt  # 用于存储证书
      - certbot-var:/var/www/certbot
    depends_on:
      - nginx-backend
volumes:
  uwsgi-socket:
  static-files:
  certbot-etc:  # 用于存储证书
  certbot-var: