version: '3'

services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=CowWeb_ver1.settings
    volumes:
      - uwsgi-socket:/tmp
      - static-files:/app/static
      - ./entrypoint.sh:/app/entrypoint.sh  # 挂载 entrypoint.sh 到容器
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  nginx-backend:
    image: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/backend.conf
      - uwsgi-socket:/tmp
      - static-files:/app/static
      - ./entrypoint.sh:/app/entrypoint.sh  # 挂载 entrypoint.sh 到容器
    depends_on:
      - web
    restart: always
volumes:
  uwsgi-socket:
  static-files:
  db_data:
