version: '3'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=CowWeb_ver1.settings
    volumes:
      - uwsgi-socket:/tmp
      - static-files:/app/static
      - ./entrypoint.sh:/app/entrypoint.sh  # 挂载 entrypoint.sh 到容器
    restart: always

  nginx-backend:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/backend.conf
      - uwsgi-socket:/tmp
      - static-files:/app/static
      - ./entrypoint.sh:/app/entrypoint.sh  # 挂载 entrypoint.sh 到容器
    depends_on:
      - web
    restart: always
volumes:
  uwsgi-socket:
  static-files:
