# Generated by Django 4.2.6 on 2023-10-24 01:28

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                error_messages={"max_length": "手机号码长度不正确", "unique": "手机号码已注册"},
                max_length=11,
                null=True,
                unique=True,
                validators=[apps.users.models.validate_mobile],
                verbose_name="手机号码",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=11, verbose_name="姓名"),
        ),
    ]
