# Generated by Django 4.2.6 on 2023-10-24 01:49

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_mobile_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                default=None,
                error_messages={"max_length": "手机号码长度不正确", "unique": "手机号码已注册"},
                max_length=11,
                null=True,
                unique=True,
                validators=[apps.users.models.validate_mobile],
                verbose_name="手机号码",
            ),
        ),
    ]
