# Generated by Django 4.2.6 on 2023-10-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cage_id",
                    models.CharField(max_length=40, unique=True, verbose_name="笼号编码"),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区号",
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
            ],
            options={
                "verbose_name": "犊牛笼",
                "verbose_name_plural": "犊牛笼",
                "db_table": "cage",
            },
        ),
        migrations.CreateModel(
            name="Calf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calf_id",
                    models.CharField(max_length=40, unique=True, verbose_name="犊牛耳标ID"),
                ),
                ("date_of_birth", models.DateField(db_index=True, verbose_name="出生日期")),
                (
                    "weight_day_add",
                    models.IntegerField(db_index=True, default=1, verbose_name="日增重"),
                ),
                (
                    "adjusted_feeding",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="临时调整饲喂量"
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
            ],
            options={
                "verbose_name": "犊牛",
                "verbose_name_plural": "犊牛",
                "db_table": "calf",
            },
        ),
        migrations.CreateModel(
            name="Pasture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="牧场"),
                ),
                (
                    "province",
                    models.CharField(db_index=True, max_length=25, verbose_name="省份"),
                ),
                (
                    "city",
                    models.CharField(db_index=True, max_length=25, verbose_name="城市"),
                ),
                (
                    "district",
                    models.CharField(db_index=True, max_length=25, verbose_name="区/县"),
                ),
                (
                    "address_detail",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="详细地址"
                    ),
                ),
            ],
            options={
                "verbose_name": "牧场",
                "verbose_name_plural": "牧场",
                "db_table": "pasture",
            },
        ),
        migrations.CreateModel(
            name="RFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rfid_id",
                    models.CharField(max_length=40, unique=True, verbose_name="RFID卡号"),
                ),
                (
                    "is_invalid",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="已作废"
                    ),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfids",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID",
                "verbose_name_plural": "RFID",
                "db_table": "rfid",
            },
        ),
        migrations.CreateModel(
            name="RFIDCage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_cage",
                        to="WebCloud.cage",
                        verbose_name="犊牛笼",
                    ),
                ),
                (
                    "rfid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_cage",
                        to="WebCloud.rfid",
                        verbose_name="RFID",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID & 犊牛笼",
                "verbose_name_plural": "RFID & 犊牛笼",
                "db_table": "rfid_cage",
            },
        ),
        migrations.CreateModel(
            name="HistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                ("rfid_id", models.CharField(max_length=40, verbose_name="RFID卡号")),
                ("cage_id", models.CharField(max_length=40, verbose_name="笼号编码")),
                ("calf_id", models.CharField(max_length=40, verbose_name="犊牛耳标ID")),
                ("day_of_birth", models.SmallIntegerField(verbose_name="日龄")),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区号",
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "adjusted_feeding",
                    models.SmallIntegerField(default=0, verbose_name="临时调整饲喂量"),
                ),
                (
                    "feeding_total_feeding",
                    models.SmallIntegerField(default=50, verbose_name="总饲喂量"),
                ),
                (
                    "temp",
                    models.FloatField(
                        blank=True,
                        default="",
                        max_length=5,
                        null=True,
                        verbose_name="饲喂温度",
                    ),
                ),
                ("mae", models.SmallIntegerField(default=50, verbose_name="早晚班次")),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_data",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "历史加奶数据",
                "verbose_name_plural": "历史加奶数据",
                "db_table": "history_data",
                "ordering": ("-c_time",),
            },
        ),
        migrations.CreateModel(
            name="FeedingStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feeding_age",
                    models.SmallIntegerField(
                        db_index=True, default=1, verbose_name="日龄"
                    ),
                ),
                (
                    "feeding_total_feeding",
                    models.SmallIntegerField(
                        db_index=True, default=50, verbose_name="总饲喂量"
                    ),
                ),
                (
                    "feeding_up",
                    models.SmallIntegerField(
                        db_index=True, default=50, verbose_name="饲喂比例"
                    ),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeding_standards",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "饲喂标准",
                "verbose_name_plural": "饲喂标准",
                "db_table": "feeding_standard",
            },
        ),
        migrations.CreateModel(
            name="CalfCage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cage_entry_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="入笼时间"
                    ),
                ),
                (
                    "cage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calf_cage",
                        to="WebCloud.cage",
                        verbose_name="犊牛笼",
                    ),
                ),
                (
                    "calf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calf_cage",
                        to="WebCloud.calf",
                        verbose_name="犊牛",
                    ),
                ),
            ],
            options={
                "verbose_name": "犊牛 & 犊牛笼",
                "verbose_name_plural": "犊牛 & 犊牛笼",
                "db_table": "calf_cage",
            },
        ),
        migrations.AddField(
            model_name="calf",
            name="pasture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calves",
                to="WebCloud.pasture",
                verbose_name="牧场",
            ),
        ),
        migrations.AddField(
            model_name="cage",
            name="pasture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cages",
                to="WebCloud.pasture",
                verbose_name="牧场",
            ),
        ),
    ]
