# Generated by Django 4.2.6 on 2023-10-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cage_id",
                    models.CharField(
                        help_text="笼号编码",
                        max_length=40,
                        unique=True,
                        verbose_name="笼号编码",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="区域",
                        max_length=10,
                        null=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="区号",
                        max_length=10,
                        null=True,
                        verbose_name="区号",
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="备注",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
            ],
            options={
                "verbose_name": "笼",
                "verbose_name_plural": "笼",
                "db_table": "cage",
            },
        ),
        migrations.CreateModel(
            name="Pasture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="id主键",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id主键",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("u_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="逻辑删除")),
                (
                    "name",
                    models.CharField(
                        help_text="工厂名称",
                        max_length=100,
                        unique=True,
                        verbose_name="工厂名称",
                    ),
                ),
                ("province", models.CharField(max_length=25, verbose_name="省份")),
                ("city", models.CharField(max_length=25, verbose_name="城市")),
                ("district", models.CharField(max_length=25, verbose_name="区/县")),
                (
                    "address_detail",
                    models.TextField(default="", max_length=500, verbose_name="详细地址"),
                ),
            ],
            options={
                "verbose_name": "牧场",
                "verbose_name_plural": "牧场",
                "db_table": "pasture",
            },
        ),
        migrations.CreateModel(
            name="RFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rfid_id",
                    models.CharField(
                        help_text="RFID卡号",
                        max_length=40,
                        unique=True,
                        verbose_name="RFID卡号",
                    ),
                ),
                (
                    "use_status",
                    models.SmallIntegerField(
                        choices=[(1, "使用中"), (2, "未使用"), (3, "作废")],
                        default=1,
                        help_text="使用状态:1-使用中,2-未使用,3-作废",
                        verbose_name="使用状态",
                    ),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfids",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID",
                "verbose_name_plural": "RFID",
                "db_table": "rfid",
            },
        ),
        migrations.CreateModel(
            name="HistoryData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="id主键",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id主键",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("u_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="逻辑删除")),
                (
                    "rfid",
                    models.CharField(
                        help_text="RFID卡号", max_length=40, verbose_name="RFID卡号"
                    ),
                ),
                (
                    "cage",
                    models.CharField(
                        help_text="笼号编码", max_length=40, verbose_name="笼号编码"
                    ),
                ),
                (
                    "cow",
                    models.CharField(
                        help_text="犊牛耳标ID", max_length=40, verbose_name="犊牛耳标ID"
                    ),
                ),
                (
                    "day_of_birth",
                    models.SmallIntegerField(help_text="日龄", verbose_name="日龄"),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="区域",
                        max_length=10,
                        null=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="区号",
                        max_length=10,
                        null=True,
                        verbose_name="区号",
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="备注",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "adjusted_feeding",
                    models.SmallIntegerField(
                        default=0, help_text="临时调整饲喂量", verbose_name="临时调整饲喂量"
                    ),
                ),
                (
                    "feeding_total_feeding",
                    models.SmallIntegerField(
                        default=50, help_text="总前饲喂量", verbose_name="总饲喂量"
                    ),
                ),
                (
                    "temp",
                    models.FloatField(
                        blank=True,
                        default="",
                        help_text="饲喂温度",
                        max_length=5,
                        null=True,
                        verbose_name="饲喂温度",
                    ),
                ),
                (
                    "mae",
                    models.SmallIntegerField(
                        default=50, help_text="早晚班次", verbose_name="早晚班次"
                    ),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_data",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "历史加奶数据",
                "verbose_name_plural": "历史加奶数据",
                "db_table": "history_data",
                "ordering": ("-c_time",),
            },
        ),
        migrations.CreateModel(
            name="Feeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feeding_age",
                    models.SmallIntegerField(
                        default=1, help_text="日龄", verbose_name="日龄"
                    ),
                ),
                (
                    "feeding_total_feeding",
                    models.SmallIntegerField(
                        default=50, help_text="总前饲喂量", verbose_name="总饲喂量"
                    ),
                ),
                (
                    "feeding_up",
                    models.SmallIntegerField(
                        default=50, help_text="饲喂比例", verbose_name="饲喂比例"
                    ),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedings",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "喂养",
                "verbose_name_plural": "喂养",
                "db_table": "feeding",
            },
        ),
        migrations.CreateModel(
            name="CowCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cow_id",
                    models.CharField(
                        help_text="犊牛耳标ID",
                        max_length=40,
                        unique=True,
                        verbose_name="犊牛耳标ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="出生日期", verbose_name="出生日期"),
                ),
                (
                    "cage_entry_date",
                    models.DateField(help_text="入笼日期", null=True, verbose_name="入笼日期"),
                ),
                (
                    "cage_out_date",
                    models.DateField(help_text="出笼日期", null=True, verbose_name="出笼日期"),
                ),
                (
                    "weight_day_add",
                    models.IntegerField(default=1, help_text="日增重", verbose_name="日增重"),
                ),
                (
                    "adjusted_feeding",
                    models.SmallIntegerField(
                        default=0, help_text="临时调整饲喂量", verbose_name="临时调整饲喂量"
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="备注",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "cage_status",
                    models.SmallIntegerField(
                        choices=[(1, "出笼"), (2, "入笼")],
                        default=1,
                        help_text="入笼状态:1-出笼,2-入笼",
                        verbose_name="入笼状态",
                    ),
                ),
                (
                    "cage_cow",
                    models.OneToOneField(
                        default=9999,
                        help_text="入住笼号",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="WebCloud.cage",
                    ),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cow_cards",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
                (
                    "rfid",
                    models.OneToOneField(
                        default=9999,
                        help_text="RFID卡号",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="WebCloud.rfid",
                    ),
                ),
            ],
            options={
                "verbose_name": "犊牛卡",
                "verbose_name_plural": "犊牛卡",
                "db_table": "cow_card",
            },
        ),
        migrations.AddField(
            model_name="cage",
            name="pasture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cages",
                to="WebCloud.pasture",
                verbose_name="牧场",
            ),
        ),
    ]
