# Generated by Django 4.2.6 on 2023-10-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calf",
            name="sex",
            field=models.SmallIntegerField(
                choices=[(1, "公"), (2, "母")],
                db_index=True,
                default=2,
                verbose_name="性别",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedingstandard",
            unique_together={("feeding_age", "pasture")},
        ),
    ]
