# Generated by Django 4.2.6 on 2023-11-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0002_calf_sex_alter_feedingstandard_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemainingMilk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                ("date", models.DateTimeField(db_index=True, verbose_name="时间")),
                (
                    "milk_volume",
                    models.FloatField(db_index=True, default=0.0, verbose_name="剩余奶量"),
                ),
                (
                    "pasture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remaining_milks",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
                (
                    "rfid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remaining_milks",
                        to="WebCloud.rfid",
                        verbose_name="rfid",
                    ),
                ),
            ],
            options={
                "verbose_name": "犊牛剩余奶量",
                "verbose_name_plural": "犊牛剩余奶量",
                "db_table": "remaining_milk",
            },
        ),
    ]
