# Generated by Django 4.2.6 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0003_remainingmilk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calf",
            name="adjusted_feeding",
            field=models.FloatField(db_index=True, default=0.0, verbose_name="临时调整饲喂量"),
        ),
        migrations.AlterField(
            model_name="calf",
            name="weight_day_add",
            field=models.FloatField(db_index=True, default=1.0, verbose_name="日增重"),
        ),
    ]
