# Generated by Django 4.2.6 on 2023-11-20 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0005_dataupdatestatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataupdatestatus",
            name="c_time",
        ),
        migrations.RemoveField(
            model_name="dataupdatestatus",
            name="is_delete",
        ),
    ]
