# Generated by Django 4.2.6 on 2023-11-20 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0006_remove_dataupdatestatus_c_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataupdatestatus",
            name="u_time",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, verbose_name="更新时间"
            ),
        ),
    ]
