# Generated by Django 4.2.6 on 2023-11-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0007_alter_dataupdatestatus_u_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=32, verbose_name="设备id"),
                ),
                ("power", models.IntegerField(db_index=True, verbose_name="电量（%）")),
                (
                    "milk_temperature",
                    models.FloatField(db_index=True, verbose_name="奶温（℃）"),
                ),
                ("boot_time", models.DateTimeField(db_index=True, verbose_name="开机时间")),
                (
                    "shutdown_time",
                    models.DateTimeField(db_index=True, verbose_name="关机时间"),
                ),
                (
                    "spare1",
                    models.CharField(db_index=True, max_length=10, verbose_name="备用1"),
                ),
                (
                    "spare2",
                    models.CharField(db_index=True, max_length=10, verbose_name="备用2"),
                ),
            ],
            options={
                "verbose_name": "设备日志",
                "verbose_name_plural": "设备日志",
                "db_table": "device_log",
                "ordering": ("-u_time",),
            },
        ),
    ]
