# Generated by Django 4.2.6 on 2023-11-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0008_devicelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="calf",
            name="birth_weight",
            field=models.FloatField(
                db_index=True, default=0.0, verbose_name="出生体重(kg)"
            ),
        ),
        migrations.CreateModel(
            name="UnlinkCalf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                (
                    "calf_id",
                    models.CharField(max_length=40, unique=True, verbose_name="犊牛编号"),
                ),
                ("date_of_birth", models.DateField(db_index=True, verbose_name="出生日期")),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(1, "公"), (2, "母")],
                        db_index=True,
                        default=2,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth_weight",
                    models.FloatField(
                        db_index=True, default=0.0, verbose_name="出生体重(kg)"
                    ),
                ),
                (
                    "weight_unlink",
                    models.FloatField(
                        db_index=True, default=0.0, verbose_name="出笼体重(kg)"
                    ),
                ),
                (
                    "date_unlink",
                    models.DateTimeField(
                        db_index=True, default="", verbose_name="出笼时间"
                    ),
                ),
                (
                    "rsn_unlink",
                    models.IntegerField(
                        choices=[(0, "无"), (1, "断奶"), (2, "死亡"), (3, "其他")],
                        db_index=True,
                        default=0,
                        verbose_name="出笼原因",
                    ),
                ),
                ("infor_unlink", models.TextField(default="", verbose_name="出笼备注信息")),
                (
                    "pasture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlink_calves",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "出笼犊牛",
                "verbose_name_plural": "出笼犊牛",
                "db_table": "unlink_calf",
                "ordering": ("-c_time",),
            },
        ),
    ]
