# Generated by Django 4.2.6 on 2023-11-21 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0009_calf_birth_weight_unlinkcalf"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidcage",
            name="bound_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="绑定时间",
            ),
            preserve_default=False,
        ),
    ]
