# Generated by Django 4.2.6 on 2023-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0012_alter_unlinkcalf_date_unlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="unlinkcalf",
            name="weight_day_add",
            field=models.FloatField(db_index=True, default=1.0, verbose_name="日增重"),
        ),
    ]
