# Generated by Django 4.2.6 on 2023-12-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WebCloud", "0013_unlinkcalf_weight_day_add"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                ("rfid_id", models.CharField(max_length=40, verbose_name="RFID卡号")),
                ("cage_id", models.CharField(max_length=40, verbose_name="笼号编码")),
                ("calf_id", models.CharField(max_length=40, verbose_name="犊牛耳标ID")),
                ("day_of_birth", models.SmallIntegerField(verbose_name="日龄")),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区号",
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "adjusted_feeding",
                    models.SmallIntegerField(default=0, verbose_name="临时调整饲喂量"),
                ),
                (
                    "feeding_total_feeding",
                    models.SmallIntegerField(default=50, verbose_name="总饲喂量"),
                ),
                (
                    "temp",
                    models.FloatField(
                        blank=True,
                        default="",
                        max_length=5,
                        null=True,
                        verbose_name="饲喂温度",
                    ),
                ),
                ("mae", models.SmallIntegerField(default=50, verbose_name="早晚班次")),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_history_data",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto历史加奶数据",
                "verbose_name_plural": "Auto历史加奶数据",
                "db_table": "auto_historydata",
                "ordering": ("-c_time",),
            },
        ),
        migrations.CreateModel(
            name="RationHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "u_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="逻辑删除"
                    ),
                ),
                ("rfid_id", models.CharField(max_length=40, verbose_name="RFID卡号")),
                ("cage_id", models.CharField(max_length=40, verbose_name="笼号编码")),
                ("calf_id", models.CharField(max_length=40, verbose_name="犊牛耳标ID")),
                ("day_of_birth", models.SmallIntegerField(verbose_name="日龄")),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="区号",
                    ),
                ),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "adjusted_feeding",
                    models.SmallIntegerField(default=0, verbose_name="临时调整饲喂量"),
                ),
                (
                    "feeding_total_feeding",
                    models.SmallIntegerField(default=50, verbose_name="总饲喂量"),
                ),
                (
                    "temp",
                    models.FloatField(
                        blank=True,
                        default="",
                        max_length=5,
                        null=True,
                        verbose_name="饲喂温度",
                    ),
                ),
                ("mae", models.SmallIntegerField(default=50, verbose_name="早晚班次")),
                (
                    "pasture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ration_history_data",
                        to="WebCloud.pasture",
                        verbose_name="牧场",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ration历史加奶数据",
                "verbose_name_plural": "Ration历史加奶数据",
                "db_table": "ration_historydata",
                "ordering": ("-c_time",),
            },
        ),
        migrations.DeleteModel(
            name="HistoryData",
        ),
    ]
